added focal point functionality
junaidbhura/fly-dynamic-image-resizer pull request #56
Opened 2022-10-12 14:07 UTC by kubiqsk

When you provide a number values inside $crop array, it will automatically detect them as a focal point and create correctly positioned image

2022-10-12 15:16 UTC, kubiqsk commented on inc/class-core.php
> +				$crop_extension = '-f' . round( $crop[0] * 100 ) . '_' . round( $crop[1] * 100 );
maybe also `floatval()` these `$crop` values?

2022-10-14 07:58 UTC, kubiqsk commented on inc/class-core.php
> +				if( is_numeric( $crop[0] ) ){
Here should be also `is_array( $crop )` part of this condition

2022-12-16 09:02 UTC, sliesensei requested changes
You should not use `intval( $size[0] );` and `intval( $size[1] );` to get destination width and height. Instead you should use `$width` and `$height` defined above. In case we are using a size name you're trying to get width and height from a string, this causes a division by 0 later.

2022-12-16 10:16 UTC, kubiqsk commented
Sorry, I will not cooperate anymore on this, because I can not wait so long and author of the plugin is not responding on forums or here, so I've created my own plugin
https://wordpress.org/plugins/better-image-sizes/

2022-12-16 10:17 UTC, closed without merging